hashicorp/terraform-github-actions

fmt/Dockerfile
init/Dockerfile
plan/Dockerfile
validate/Dockerfile

This is needed as users may have statefiles that have been applied using
the latest terraform version but are seeing failures when running the
Github Actions.
Fixes #2
Here is the `terraform init` failure message that I'm seeing from the actions:
```
Already have image (with digest): gcr.io/github-actions-development/action-runner:latest
Initializing modules...
- module.network
Getting source "../../modules/example/"
- module.example.example
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error: 
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.10'
Please run at …
```

Update base Docker image version to be v0.11.10

---

init/entrypoint.sh
plan/entrypoint.sh
validate/entrypoint.sh

- New TF_ACTION_TFE_TOKEN environment variable for specifying the
terraform enteprise token.
- New TF_ACTION_TFE_HOSTNAME environment variable for specifying the
hostname of your TFE installation. Defaults to app.terraform.io
- Don't use workspace select unless workspace is not equal to
"default". We need to do this because the remote backend doesn't support
calling workspace select "default".
Fixes #9

Add Terraform Enterprise support

---

fmt/entrypoint.sh
init/entrypoint.sh
plan/entrypoint.sh
validate/entrypoint.sh

Adds
*Workflow: `<workflow name>`, Action: `<action name>`*
To comments so users with multiple actions/workflows can trace back the comments.
Closes #13

Add action and workflow names to output

---

fmt/Dockerfile
fmt/entrypoint.sh
init/Dockerfile
plan/Dockerfile
validate/Dockerfile

Take Andrew's PR (#20) and add a fix for the new flags to `fmt` in 0.12.
Also fixes a bug that was there previously where if `fmt` failed due to validation errors we would print a malformed comment.

Adds support for terraform v0.12.0

---

apply/Dockerfile
fmt/Dockerfile
init/Dockerfile
plan/Dockerfile
validate/Dockerfile

This PR bumps the Docker base images to those built for Terraform 0.12.3.
Just a question: shouldn't we use `FROM hashicorp/terraform:latest` instead?
Since all Terraform files touched with a newer version can't be validated with an earlier version, having an old version in these actions means that CI breaks whenever any developer upgrades Terraform.

Update Docker images to Terraform 0.12.3

---

apply/entrypoint.sh
fmt/entrypoint.sh
init/entrypoint.sh
plan/entrypoint.sh
validate/entrypoint.sh

Enable colors to add some flair to the action logs. To keep comments sane, we strip the ANSI color codes before posting.
This is mainly in response to the conclusion of #55. While the coloring isn't as helpful as Github's diff syntax coloring. It's better than nothing when looking at action output logs.

Enable output coloring for logs

---

apply/entrypoint.sh
fmt/entrypoint.sh
init/entrypoint.sh
plan/entrypoint.sh
validate/entrypoint.sh

In the event of a non-PR workflow, the actions would still attempt to
post output to the non-existent PR URL. This change checks to see if jq
parsed a "null" URL, and doesn't run curl if that is the case.

Do Not Try to Comment on Non-PR Builds (fixes #50)

---

apply/entrypoint.sh
fmt/entrypoint.sh
init/entrypoint.sh
plan/entrypoint.sh
validate/entrypoint.sh

We've added the `$TF_ACTION_WORKING_DIRECTORY` to the output for the
action comments, so that we can differentiate between actions that get
applied to multiple directories in the same PR.
Fixes #41
Fixes #66

Append working directory to action output

---

CHANGELOG.md
src/main.sh
src/terraform_fmt.sh

This is more of a band-aid than a proper solution. It's probably worth just eliminating `-recursive` altogether but this will do for now.
Fixes #90.

Do not use -recursive option for Terraform 0.11.x

---

src/terraform_apply.sh
src/terraform_fmt.sh
src/terraform_init.sh
src/terraform_plan.sh
src/terraform_validate.sh

This makes the commenting much more reliable when the plan output is hundreds of lines long. 
Without this I would just get
```
/entrypoint.sh: line 99: jq: Argument list too long
```
But with this change it works as it should.
I also made it cut the error output if it is too long. This can happen when it failed to fetch the status of some resource.

Pass comments through pipes instead of as command line arguments

---

src/terraform_apply.sh
src/terraform_fmt.sh
src/terraform_init.sh
src/terraform_plan.sh
src/terraform_validate.sh

When `${*}` is quoted and does not contain any value, an empty string will be used instead. This causes some `terraform` commands to operate on an empty directory, not the current working directory.

Fixing improper handling of arguments

---

README.md
action.yml
examples/arguments.md
examples/backends.md
examples/credentials-file.md
examples/variables.md
src/main.sh

Supersedes #113. This allows a user to configure the CLI credentials file to authenticate to Terraform Cloud/Enterprise.

Adding CLI credentials file

---

README.md
src/main.sh

Automatically download the latest version when `tf_actions_version` set to `latest`.
refs: #94

Support to use the latest version of Terraform

---

src/terraform_output.sh

When output is multi-line string, the `tf_actions_output` in `output` subcommand collapses. It is because output is not quoted in `src/terraform_output.sh`. And according to the discussion below, escape is required before `set-output`.
https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870

Fix output collapse

---

Dockerfile

`mkdir` is not necessary in Dockerfile.
You can simply use WORKDIR but in case you just copy from src to /src, so it can be ommited.
Additionally, as alpine uses sh by default, I don't think you have to speficy /bin/sh in RUN, too.
```Dockerfile
FROM alpine:3 
RUN apk add --update --no-cache bash ca-certificates curl git jq openssh
COPY src /src
ENTRYPOINT ["/src/main.sh"]
```

remove mkdir from dockerfile

---

README.md
action.yml
src/terraform_plan.sh

Subsequent actions may want to us the `terraform plan` output, e.g. sending it as email, posting to Slack, etc.
This PR sets this output as `tf_actions_plan_output` from the action

Let plan action output the plan-output

---

src/main.sh
src/terraform_import.sh

hi, I want to use `terraform import fastly_service_v1.xxx xxxx`.
because I want to execute the `plan` after getting the same state as the real fastly service.

add import subcommand

---

README.md
examples/tainting.md
src/main.sh
src/terraform_taint.sh

I found the need to be able to run `terraform taint` in a workflow. 
It takes a space-delimited list in the `args` option in the `with` block. Additionally `terraform taint` runs with the `-allow-missing` flag.

Adding terraform taint actions

---

src/main.sh

The old behaviour didn't cause issues, because setting a working dir of
"" is equivalent to setting ".". But better to fix this behaviour.

Fix a condition

---

README.md

Maybe this is too much hand holding, but these actions tend to be relatively repetitive wrt inputs that they need and those inputs should pretty much always be variablized.  This PR provides an example of how to variablize things like the working directory and the TF version so they are managed in a single assignment rather than 2-6 assignments.

Add variablized example
